services:
  postgis:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  geoserver:
    image: kartoza/geoserver
    depends_on:
      - postgis
    environment:
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
      org.geoserver.web.csp.strict: "false"
      HTTP_SCHEME: "https"
      HTTP_PROXY_NAME: ${CODESPACE_NAME}-8080.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
      HTTP_PROXY_PORT: "443"
    ports:
      - "8080:8080"
    volumes:
      - gs_data:/opt/geoserver/data_dir

volumes:
  pg_data:
  gs_data:
